### ISSUE TITLE
Errors with comp_loudness and comp_sharpness

### ISSUE THREAD

**Issue by Alann72** [Eomys/MoSQITo#30] opened 2021-12-14 10:49 UTC
Hi,
I've got a problem when i want to calculate loudness (or sharpness) with a 44 kHz sampled signal.
I've got this error : 
`ValueError: operands could not be broadcast together with shapes (64,) (367265,) (64,) `
I don't have the problem if i use a short part of the signal
`signal=signal[0:1000]`
No problem if i use a 48 kHz resampled version of the file

**Comment by mglesser** [comment] 2021-12-14 17:31
Hi, thanks for the feedback. Actually, as per the ISO standard, the signal shall be sampled at 48 kHz for the loudness/sharpness computation (because some numerical filters are only defined for this specific sampling frequency). But normally the code should be robust to other sampling frequencies, or at least give you a meaningfull feedback. I'll try to have a look and will let you know. I'm very busy in the next days, so I cannot promise it will be quick!

**Comment by mglesser** [comment] 2022-02-15 10:55
Hi @Alann72, I've finally managed to check the behavior of the loudness and sharpness computation with a 44.1 KHz sampled signal. On my side, it work just fine. I've added a unit test for this feature (it will be soon merged to the repository)

If you are still in trouble maybe you can send me your wav file so that I can have a look.

**Comment by lakefield7** [comment] 2022-06-22 01:21
Hi, 
I installed mosqito-1.0.8 and tried to compute the loudness of 44.1 kHz sampled signal.
I've got below error :

  File "c:/Users/09021876/Documents/T-PALET-sound/sound2-0.py", line 88, in <module>
    N, N_spec, bark_axis, time_axis = loudness_zwtv(sig, frate2, field_type="free")
  File "C:\Users\09021876\jobsound\lib\site-packages\mosqito\sq_metrics\loudness\loudness_zwtv\loudness_zwtv.py", line 49, in loudness_zwtv
    spec_third, time_axis, _ = _third_octave_levels(signal, fs)
  File "C:\Users\09021876\jobsound\lib\site-packages\mosqito\sq_metrics\loudness\loudness_zwtv\_third_octave_levels.py", line 37, in _third_octave_levels    raise ValueError("""ERROR: Sampling frequency shall be equal to 48 kHz""")
ValueError: ERROR: Sampling frequency shall be equal to 48 kHz

**Comment by mglesser** [comment] 2022-08-19 13:01
Hi,
Sorry for this late answer. As mentionned in the error message, the loudness algorithm, by design, only support sampling frequency equal to 48 kHz. If you have to deal with signals at another sampling frequency, I suggest you to use the MOSQITO load function: 
```
from mosqito.utils import load
sig, fs = load("<path>/arctic_a0001.wav", wav_calib=1)
```
This way, the signal will be resampled automatically. And you will be able to compute the loudness : 
`N, N_spec, bark_axis, time_axis = loudness_zwtv(sig, fs, field_type="free")`
I tried with your signal and it is working well.
![image](https://user-images.githubusercontent.com/60893296/185623789-7739bd9d-7cbc-4266-a9eb-2f9153e7a162.png)

**Closed** 2023-03-07 14:23 UTC
